FROM python:3.13-alpine

WORKDIR /app

COPY requirements.lock .

RUN pip install --no-cache-dir -r requirements.lock

COPY . .

CMD ["uvicorn", "spaceship.app:app", "--host", "0.0.0.0", "--port", "8000"]
